Traceback (most recent call last):
  File "/home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py", line 2, in <module>
    import main
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py", line 6, in <module>
    main.main(sys.argv[1])
  File "main.pyx", line 138, in main.main (main.c:4660)
    Fock, inp.mSCF[a], Dnew, eproj, err = do_embedding(a, inp,
  File "scf.pyx", line 158, in scf.do_embedding (scf.c:5394)
    cycles, conv, Fock=FAA, hcore=hcore, sigma=inp.mol[A].smearsig)
AttributeError: 'Mole' object has no attribute 'smearsig'
<class 'pyscf.gto.mole.Mole'> does not have attributes  smearsig
=>> PBS: job killed: walltime 259242 exceeded limit 259200
<class 'pyscf.gto.mole.Mole'> does not have attributes  smearsig
=>> PBS: job killed: walltime 345620 exceeded limit 345600
/var/spool/torque/mom_priv/jobs/5158271.mesabim3.msi.umn.edu.SC: line 26: 16876 Killed                  python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.inp > /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.out
/var/spool/torque/mom_priv/jobs/5160030.mesabim3.msi.umn.edu.SC: line 26: 11016 Killed                  python /home/goodpast/graha682/code/python/freeze_and_thaw/cython/cmain.py /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.inp > /panfs/roc/groups/13/goodpast/graha682/201706_MOF5/201802_FT/mof5_node_ah2.out
=>> PBS: job killed: walltime 345626 exceeded limit 345600
